export const INIT = 'INIT';

// data fetch & API actions
export const REQUEST_PRESENTATION = 'REQUEST_PRESENTATION';
export const FETCH_PRESENTATION = 'FETCH_PRESENTATION';
export const RECEIVE_PRESENTATION = 'RECEIVE_PRESENTATION';
export const FETCH_PRESENTATION_ERROR = 'FETCH_PRESENTATION_ERROR';
export const FETCH_PRESENTATION_CANCEL = 'FETCH_PRESENTATION_CANCEL';

export const REQUEST_PRESENTATION_LIST = 'REQUEST_PRESENTATION_LIST';
export const FETCH_PRESENTATION_LIST = 'FETCH_PRESENTATION_LIST';
export const RECEIVE_PRESENTATION_LIST = 'RECEIVE_PRESENTATION_LIST';
export const FETCH_PRESENTATION_LIST_ERROR = 'FETCH_PRESENTATION_LIST_ERROR';
export const FETCH_PRESENTATION_LIST_CANCEL = 'FETCH_PRESENTATION_LIST_CANCEL';

export const START_MASTER_WEBSOCKET = 'START_MASTER_WEBSOCKET';
export const STOP_MASTER_WEBSOCKET = 'STOP_MASTER_WEBSOCKET';

export const START_SLAVE_WEBSOCKET = 'START_SLAVE_WEBSOCKET';
export const STOP_SLAVE_WEBSOCKET = 'STOP_SLAVE_WEBSOCKET';

// UI actions
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const START_PRESENTATION = 'START_PRESENTATION';
export const END_PRESENTATION = 'END_PRESENTATION';
export const SHOW_TABLE_OF_CONTENTS = 'SHOW_TABLE_OF_CONTENTS';
export const HIDE_TABLE_OF_CONTENTS = 'HIDE_TABLE_OF_CONTENTS';
export const SHOW_TOOLS = 'SHOW_TOOLS';
export const HIDE_TOOLS = 'HIDE_TOOLS';
export const SHOW_PAGE = 'SHOW_PAGE';
export const REQUEST_PAGE = 'REQUEST_PRESENTATION_PAGE';
export const REQUEST_STEP = 'REQUEST_STEP';
export const NEXT_STEP = 'NEXT_STEP';
export const PREVIOUS_STEP = 'PREVIOUS_STEP';
export const SET_MODE = 'SET_MODE';
export const SET_SLAVE_MASTER = 'SET_MASTER_SLAVE';
export const SOCKET_OPENED = 'SOCKET_OPENED';

export const MODES = {
    VR: 'VR',
    HTML: 'HTML'
};

export const MASTER_SLAVE = {
    SL: 'SL',
    MS: 'MS',
    NONE: 'NONE'
}