// data fetch & API actions
export const REQUEST_PRESENTATION = "REQUEST_PRESENTATION";
export const FETCH_PRESENTATION = "FETCH_PRESENTATION";
export const RECEIVE_PRESENTATION = "RECEIVE_PRESNTATION";
export const FETCH_PRESENTATION_ERROR = "FETCH_PRESENTATION_ERROR";

// UI actions
export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const START_PRESENTATION ="START_PRESENTATION";
export const END_PRESENTATION = "END_PRESENTATION";
export const SHOW_TABLE_OF_CONTENTS = "SHOW_TABLE_OF_CONTENTS";
export const HIDE_TABLE_OF_CONTENTS = "HIDE_TABLE_OF_CONTENTS";
export const SHOW_TOOLS = "SHOW_TOOLS";
export const HIDE_TOOLS = "HIDE_TOOLS";
export const SHOW_PAGE = "SHOW_PAGE";
export const REQUEST_PAGE = "REQUEST_PRESENTATION_PAGE";
export const REQUEST_STEP = "REQUEST_STEP";
export const NEXT_STEP = "NEXT_STEP";
export const PREVIOUS_STEP = "PREVIOUS_STEP";